name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      - name: Create environment files
        run: |
          # Debug to verify API key is set
          echo "API key length: ${#FIREBASE_API_KEY}"
          
          # Create environment files with proper API key
          echo 'export const environment = {
            production: false,
            firebase: {
              apiKey: "${{ secrets.FIREBASE_API_KEY }}",
              authDomain: "zip-zap-post.firebaseapp.com",
              projectId: "zip-zap-post",
              storageBucket: "zip-zap-post.firebasestorage.app",
              messagingSenderId: "272404494518",
              appId: "1:272404494518:web:559921f865c30483838e17"
            }
          };' > src/environments/environment.ts
          
          echo 'export const environment = {
            production: true,
            firebase: {
              apiKey: "${{ secrets.FIREBASE_API_KEY }}",
              authDomain: "zip-zap-post.firebaseapp.com",
              projectId: "zip-zap-post",
              storageBucket: "zip-zap-post.firebasestorage.app",
              messagingSenderId: "272404494518",
              appId: "1:272404494518:web:559921f865c30483838e17"
            }
          };' > src/environments/environment.prod.ts
          
          # Debug the generated files (masked for security)
          echo "environment.ts contains apiKey with length: $(grep -o 'apiKey:.*",' src/environments/environment.ts | wc -c)"
          echo "environment.prod.ts contains apiKey with length: $(grep -o 'apiKey:.*",' src/environments/environment.prod.ts | wc -c)"
      
      - run: npm ci
      - run: npm run build
      
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ZIP_ZAP_POST }}'
          channelId: live
          projectId: zip-zap-post
          entryPoint: "."