name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      # Create environment files
      - name: Create environment files
        run: |
          echo "export const environment = {
            production: false,
            firebase: ${{ secrets.FIREBASE_CONFIG }}
          };" > src/environments/environment.ts
          
          echo "export const environment = {
            production: true,
            firebase: ${{ secrets.FIREBASE_CONFIG }}
          };" > src/environments/environment.prod.ts
      
      - run: npm ci
      - run: npm run build:prod
      
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ZIP_ZAP_POST }}'
          channelId: live
          projectId: zip-zap-post